### ISSUE TITLE
Input streams not closed when accessed from another thread

### ISSUE THREAD

**Issue by danieleplgr84** [ETSGlobal/ETSPaymentOgoneBundle#58]
Sometimes when calling a method to decode an image into Bitmap (ex: BitmapFactory.decodeStream(...) ) in a thread it is possible that the stream is already open. It seems to happen because in some methods (for example "processContentProviderMedia" ) the 

"process();" async method execs before the 

} finally {
            close(inputStream);
            close(outStream);
}

that should close the stream.

The solution seems to be to move the process() line after the finally block and it should works fine.

**Comment by ch3ric** [comment]
Hello,
I don't think this issue is related to our bundle.
So I close this issue, but do not hesitate to re-open and add more details if it is relevant.
